name = "your-project-name"
type = "javascript"
account_id = "your-account-id"
workers_dev = true
compatibility_date = "2023-10-01"

[build]
command = "npm run build"
[build.upload]
main = "dist/index.js" # Ensure this points to your entry-point file
